### ISSUE TITLE
Refactor Formatting For Simplicity and Readability  

### ISSUE THREAD

**Issue by ChiefMateStarbuck** [elves/awesome-elvish#23]
[Awesome-go's](https://github.com/avelino/awesome-go#audio-and-music) formatting features a clean one line description while being uncluttered with links. This is a proposition to emulate that formatting.

**Comment by krader1961** [comment]
> ...features a clean one line description...

Technically a "single sentence description" but I grok what you're saying. I'm in agreement that the current [Awesome Elvish](https://github.com/elves/awesome-elvish) document is overly verbose and would be easier to read if link details were hidden. I suspect the original author chose the current format so the link could by copy/pasted into an Elvish `use` statement and because of the `epm:install` example. It's not clear the readability trade-off is worth the ability to copy/paste the package string (as opposed to the link).

Unsurprisingly there is at least one deviation in the Awesome Elvish document from the usual way to write such links: `Package zzamboni/elvish-completions` should be `Package github.com:/zzamboni/elvish-completions` to match the other links. That sort of deviation from the norm might be less common if every link of that type were written in `[short description](url)` form in the markdown document.

**Comment by zzamboni** [comment]
I admit I've also never been fully happy with the structure of this list. The main thing is that we have two levels: packages and libraries. A package may contain multiple disparate libraries, so it doesn't always make sense to list them together.

I think maybe a better format would be tables like this:

| library | package | description |
|------|-------|------|
| [git](https://github.com/zzamboni/elvish-modules/blob/master/alias.org) | [github.com/zzamboni/elvish-modules](https://github.com/zzamboni/elvish-modules/) | Support for persistent aliases and for parsing bash-style alias commands. |

That way every library could be listed in its own corresponding section, while still having a link to the package.

This would require some extra work for the initial conversion and for maintenance, but it might be worth it for readability.

**Comment by ChiefMateStarbuck** [comment]
FYI: [elvish is now on awesome go](https://github.com/avelino/awesome-go/pull/3651)

**Comment by xiaq** [comment]
I did an extensive reformatting, please let me know what can be improved further!
